(()=>{
const app=document.getElementById('app');const steps=['landing','asset','rights','activation','event','materiality','posture','result'];
let s={screen:'landing',asset:null,activation:null,event:null,materiality:{},posture:{},route:null,postureResult:null};
try{const x=JSON.parse(localStorage.getItem('anode-gov-checkup'));if(x)s={...s,...x}}catch(e){}
const save=()=>localStorage.setItem('anode-gov-checkup',JSON.stringify(s));
function progress(){const i=Math.max(0,steps.indexOf(s.screen));document.getElementById('progressIndex').textContent=String(i).padStart(2,'0');document.getElementById('progressLabel').textContent=steps[i].toUpperCase();document.getElementById('progressFill').style.width=(i/(steps.length-1)*100)+'%';document.querySelectorAll('.progress-steps li').forEach((el,n)=>el.classList.toggle('active',n<=i));}
function go(x){s.screen=x;save();render();window.scrollTo({top:0,behavior:'smooth'})}
function btn(txt,fn,primary=false){const b=document.createElement('button');b.className='btn'+(primary?' primary':'');b.innerHTML=txt;b.onclick=fn;return b}
function shell(html){app.innerHTML=`<section class="screen">${html}</section>`;progress()}
function landing(){shell(`<div class="screen-grid"><div><div class="eyebrow">ANODE / INTERACTIVE RESEARCH 001</div><h1 class="hero-title">YOU BOUGHT<br>THE TOKEN.<br><span class="outline">WHAT ELSE DID YOU BUY?</span></h1><p class="lede">Owning the asset does not tell you what governance rights you own.</p><p class="body-copy">Explore the control surface behind a digital asset and see how a professional tokenholder might route governance decisions.</p><div class="hero-meta"><div>12 NETWORKS</div><div>7 GOVERNANCE ARCHETYPES</div><div>~3 MINUTES</div></div><div class="actions" id="a"></div></div><aside class="side-note"><div class="big-number">01</div><p>RIGHTS → EVENTS → MATERIALITY → POLICY → DECISION → EXECUTION → EVIDENCE</p></aside></div>`);document.getElementById('a').append(btn('START THE CHECKUP →',()=>go('asset'),true));}
function asset(){shell(`<div class="eyebrow">01 / ASSET</div><h1 class="screen-title">WHAT DO<br><span class="outline">YOU HOLD?</span></h1><div class="asset-grid" id="grid"></div>`);const g=document.getElementById('grid');Object.entries(ASSETS).forEach(([k,a])=>{const b=document.createElement('button');b.className='asset-card';b.innerHTML=`<span class="ticker">${k}</span><span class="asset-name">${a.name}</span><span class="archetype">${a.archetype}</span><span class="arrow">↗</span>`;b.onclick=()=>{s.asset=k;go('rights')};g.append(b)})}
function rights(){const a=ASSETS[s.asset];if(!a)return go('asset');shell(`<div class="eyebrow">02 / CONTROL SURFACE</div><div class="profile-header"><div><div class="profile-token">${s.asset}</div><div class="profile-name">${a.name}</div></div><div class="profile-page">${a.archetype}</div></div><div class="data-strip"><div class="data-cell"><span class="data-label">ARCHETYPE</span><div class="data-value">${a.archetype}</div></div><div class="data-cell"><span class="data-label">ACTIVATION</span><div class="data-value">${a.activation}</div></div><div class="data-cell"><span class="data-label">SHARED AUTHORITY</span><div class="data-value">${a.shared}</div></div><div class="data-cell"><span class="data-label">RESEARCH DATE</span><div class="data-value">${RESEARCH_DATE}</div></div></div><h2 class="screen-title">WHAT CAN THIS<br><span class="outline">ASSET GOVERN?</span></h2><div class="surface-list">${a.surfaces.map(x=>`<div>${x}</div>`).join('')}</div><div class="back-row" id="nav"></div>`);document.getElementById('nav').append(btn('← BACK',()=>go('asset')),btn('CHECK ACTIVATION →',()=>go('activation'),true))}
function choices(title,copy,opts,next){shell(`<div class="eyebrow">03 / ACTIVATION</div><h1 class="screen-title">${title}</h1><p class="lede">${copy}</p><div class="choice-list" id="c"></div><div class="back-row" id="n"></div>`);const c=document.getElementById('c');opts.forEach(([v,t,d])=>{const b=document.createElement('button');b.className='choice-card';b.innerHTML=`<span class="choice-code">↗</span><span class="choice-title">${t}</span><span class="choice-copy">${d}</span>`;b.onclick=()=>{s.activation=v;go(next)};c.append(b)});document.getElementById('n').append(btn('← BACK',()=>go('rights')))}
function activation(){const a=ASSETS[s.asset];choices('DO YOU ACTUALLY HAVE<br><span class="outline">USABLE POWER?</span>',`For ${s.asset}, the reviewed governance path is: ${a.activation}.`,[['yes','YES','Governance power is currently activated.'],['no','NO','The asset is held, but the governance right is not activated.'],['unsure','NOT SURE','Activation state needs verification.'],['na','NOT APPLICABLE','No conventional activation path applies.']],'event')}
const EVENTS={routine:['ROUTINE','Scheduling, duplicates, housekeeping.'],economic:['ECONOMIC','Fees, issuance, burns, buybacks, incentives.'],risk:['RISK','Collateral, oracle, security, exposure limits.'],strategic:['STRATEGIC','Expansion, acquisition, ecosystem direction.'],constitutional:['CONSTITUTIONAL','Quorum, chambers, delegation, security councils.'],legal:['LEGAL / REGULATORY','Entity, classification, conflicts, regulated clients.'],emergency:['EMERGENCY','Exploit, pause, attack, emergency upgrade.']};
function event(){shell(`<div class="eyebrow">04 / EVENT</div><h1 class="screen-title">WHAT<br><span class="outline">CHANGED?</span></h1><p class="lede">The unit of analysis is the governance event.</p><div class="choice-list" id="c"></div><div class="back-row" id="n"></div>`);const c=document.getElementById('c');Object.entries(EVENTS).forEach(([k,[t,d]])=>{const b=document.createElement('button');b.className='choice-card';b.innerHTML=`<span class="choice-code">↗</span><span class="choice-title">${t}</span><span class="choice-copy">${d}</span>`;b.onclick=()=>{s.event=k;go('materiality')};c.append(b)});document.getElementById('n').append(btn('← BACK',()=>go('activation')))}
function qrow(key,title){return `<div class="question-row"><div class="question-copy"><strong>${title}</strong></div><div class="segmented">${['yes','no'].map(v=>`<button data-k="${key}" data-v="${v}" class="${s.materiality[key]===v?'selected':''}">${v.toUpperCase()}</button>`).join('')}</div></div>`}
function materiality(){shell(`<div class="eyebrow">05 / MATERIALITY</div><h1 class="screen-title">TRIAGE BEFORE<br><span class="outline">PARTICIPATION.</span></h1><p class="lede">Materiality is portfolio-specific.</p><div class="question-stack">${qrow('material','Could this materially change economics, risk or control?')}${qrow('major','Does it involve fees, issuance, burns, a major treasury action, upgrade or constitutional change?')}${qrow('legal','Is there unresolved legal, mandate, conflict or compliance ambiguity?')}${qrow('emergency','Is there an exploit, capture attempt, pause or short-fuse emergency?')}</div><div class="back-row" id="n"></div>`);document.querySelectorAll('[data-k]').forEach(b=>b.onclick=()=>{s.materiality[b.dataset.k]=b.dataset.v;save();materiality()});document.getElementById('n').append(btn('← BACK',()=>go('event')),btn('SET POSTURE →',()=>{computeRoute();go('posture')},true))}
function computeRoute(){const m=s.materiality;if(m.emergency==='yes'||s.event==='emergency')s.route='EMERGENCY';else if(m.legal==='yes'||s.event==='legal')s.route='LEGAL / COMPLIANCE';else if(m.major==='yes'||(m.material==='yes'&&['economic','strategic','constitutional'].includes(s.event)))s.route='INVESTMENT ESCALATION';else if(m.material==='yes'||s.event==='risk')s.route='ANALYST REVIEW';else if(s.event==='routine'&&m.material==='no')s.route='ARCHIVE';else s.route='MONITOR'}
function prow(key,title){return `<div class="question-row"><div class="question-copy"><strong>${title}</strong></div><div class="segmented">${['yes','no'].map(v=>`<button data-p="${key}" data-v="${v}" class="${s.posture[key]===v?'selected':''}">${v.toUpperCase()}</button>`).join('')}</div></div>`}
function posture(){shell(`<div class="eyebrow">06 / POLICY POSTURE</div><h1 class="screen-title">VOTE. DELEGATE.<br><span class="outline">MONITOR. ABSTAIN.</span></h1><div class="route-preview"><div><span class="route-label">CURRENT EVENT ROUTING</span><div class="route-title">${s.route||'—'}</div></div></div><div class="question-stack">${prow('material','Is governance material to this position?')}${prow('expertise','Does the holder have internal governance expertise and capacity?')}${prow('delegate','Is a credible approved delegate available?')}${prow('legal','Are material legal/compliance constraints unresolved?')}${prow('infrequent','Are material events infrequent but costly to miss?')}</div><div class="back-row" id="n"></div>`);document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{s.posture[b.dataset.p]=b.dataset.v;save();posture()});document.getElementById('n').append(btn('← BACK',()=>go('materiality')),btn('GENERATE PROFILE →',()=>{computePosture();go('result')},true))}
function computePosture(){const p=s.posture;if(p.legal==='yes')s.postureResult='RESTRICTED';else if(p.material==='no')s.postureResult='PASSIVE';else if(p.infrequent==='yes')s.postureResult='MONITORED';else if(p.material==='yes'&&p.expertise==='yes')s.postureResult='ACTIVE';else if(p.material==='yes'&&p.delegate==='yes')s.postureResult='DELEGATED';else s.postureResult='MONITORED'}
function result(){if(!s.asset)return go('asset');computeRoute();computePosture();const a=ASSETS[s.asset];shell(`<div class="eyebrow">07 / YOUR GOVERNANCE PROFILE</div><div class="result-hero"><div class="ticker">${s.asset}</div><div class="architecture">${a.name} / ${a.archetype}</div></div><div class="result-bands"><div class="result-band signal"><span class="label">ILLUSTRATIVE DEFAULT POSTURE</span><div class="value">${s.postureResult}</div></div><div class="result-band"><span class="label">CURRENT EVENT ROUTING</span><div class="value">${s.route}</div></div></div><div class="chain"><span class="active">RIGHTS</span><span class="active">EVENTS</span><span class="active">MATERIALITY</span><span class="active">POLICY</span><span>DECISION</span><span>EXECUTION</span><span>EVIDENCE</span></div><div class="result-grid"><div><div class="result-block"><h3>CONTROL SURFACE</h3><div class="surface-list">${a.surfaces.map(x=>`<div>${x}</div>`).join('')}</div></div><div class="result-block"><h3>WATCH</h3><div class="watch-list">${a.watch.map(x=>`<div>${x}</div>`).join('')}</div></div></div><aside><div class="result-block"><h3>ACTIVATION</h3><p>${a.activation}</p></div><div class="result-block"><h3>SHARED AUTHORITY</h3><p>${a.shared}</p></div><div class="result-block"><h3>RESEARCH NOTE</h3><p>Illustrative research workflow — not legal, investment, tax or compliance advice.</p></div></aside></div><div class="actions" id="a"></div><p class="disclaimer">RESEARCH CURRENT THROUGH ${RESEARCH_DATE} UNLESS OTHERWISE NOTED.</p>`);const acts=document.getElementById('a');acts.append(btn('COPY RESULT ↗',()=>navigator.clipboard?.writeText(`ANODE GOVERNANCE RIGHTS CHECKUP\n${s.asset} — ${a.name}\nPosture: ${s.postureResult}\nEvent routing: ${s.route}\nActivation: ${a.activation}\nShared authority: ${a.shared}`)),btn('START OVER ↺',reset),btn('EXPLORE ANODE ↗',()=>window.open(ANODE_URL,'_blank')))}
function reset(){localStorage.removeItem('anode-gov-checkup');s={screen:'landing',asset:null,activation:null,event:null,materiality:{},posture:{},route:null,postureResult:null};render()}
document.getElementById('resetHeader').onclick=reset;
function render(){({landing,asset,rights,activation,event,materiality,posture,result}[s.screen]||landing)()}
render();
})();
