const HANDBOOK_URL="https://www.anode.gg/";
const ANODE_URL="https://www.anode.gg/";
const RESEARCH_DATE="25 AUGUST 2026";
const ASSETS={
UNI:{name:"UNISWAP",archetype:"EXECUTABLE TOKEN GOVERNANCE",activation:"Delegation / self-delegation",shared:"Timelock",surfaces:["Protocol fees","Treasury allocation","Governance configuration","Executable protocol actions"],watch:["Proposal threshold","Quorum","Delegation state","Protocol fees","Treasury actions","Timelock execution"]},
AAVE:{name:"AAVE",archetype:"EXECUTABLE + SECURITY CONTROLS",activation:"Direct or delegated",shared:"Security review / multichain",surfaces:["Protocol deployments","Risk configuration","Treasury operations","Service providers","Governance architecture","Token economics"],watch:["Treasury","Buybacks","Risk parameters","Deployments","Upgrades","Emergency controls"]},
ARB:{name:"ARBITRUM",archetype:"CONSTITUTIONAL TOKEN GOVERNANCE",activation:"Direct or delegated",shared:"Security Council",surfaces:["Treasury","Governance rules","Constitutional changes","Ecosystem programs","Protocol-related actions"],watch:["Constitutional classification","Treasury programs","Security Council","Execution scheduling"]},
OP:{name:"OPTIMISM",archetype:"BICAMERAL / MULTI-CONSTITUENCY",activation:"Direct or delegated",shared:"Citizens’ House",surfaces:["Capital allocation","Ratification","Representative selection","Governance rules","Protocol upgrade checks"],watch:["Token House","Citizens’ House","Protocol upgrades","Delegation"]},
LDO:{name:"LIDO",archetype:"TOKEN + STETH SAFEGUARD LAYER",activation:"Token voting / delegation",shared:"stETH Dual Governance",surfaces:["Protocol configuration","Treasury","Upgrades","Service relationships","Governance architecture"],watch:["Dual Governance","Emergency brakes","Easy Track","Upgrades","Delegation"]},
COMP:{name:"COMPOUND",archetype:"GOVERNOR BRAVO-STYLE EXECUTABLE",activation:"Delegation / self-delegation",shared:"Timelock",surfaces:["Protocol configuration","Executable governance actions","Treasury / service-provider decisions"],watch:["Proposal threshold","Delegated voting power","Protocol changes","Timelock execution"]},
SKY:{name:"SKY",archetype:"LOCKED-TOKEN EXECUTIVE GOVERNANCE",activation:"Lock / activation / delegation",shared:"GSM delay",surfaces:["Protocol parameters","Executive actions","Treasury / economic decisions","Governance configuration"],watch:["Migration rules","Executive votes","GSM delay","Delegation"]},
ENS:{name:"ETHEREUM NAME SERVICE",archetype:"TOKEN DAO + CONSTRAINED SECURITY BODY",activation:"Delegation / self-delegation",shared:"Security Council",surfaces:["Treasury","DAO policy","Constitutional rules","Service-provider programs","Executable governance"],watch:["Delegation","Constitutional changes","Security Council","Treasury"]},
DOT:{name:"POLKADOT",archetype:"TRACK-BASED OPENGOV",activation:"Direct / track delegation",shared:"Track-specific rules",surfaces:["Treasury","Runtime changes","Protocol parameters","Governance administration","Monetary policy"],watch:["Track / origin","Issuance","Treasury","Runtime upgrades","Delegation"]},
ADA:{name:"CARDANO",archetype:"REPRESENTATIVE CONSTITUTIONAL",activation:"DRep representation",shared:"SPOs + Constitutional Committee",surfaces:["Protocol parameters","Treasury withdrawals","Hard forks","Constitutional governance"],watch:["DRep delegation","Constitutional Committee","Treasury","Hard forks"]},
ATOM:{name:"COSMOS HUB",archetype:"STAKING-LINKED DELEGATED",activation:"Bonded stake / validator representation",shared:"Validator-delegator override",surfaces:["Signaling","Parameters","Software upgrades","Community-pool decisions"],watch:["Validator voting behavior","Direct override","Software upgrades","Community pool"]},
AVAX:{name:"AVALANCHE",archetype:"SOCIAL / CLIENT-ADOPTION PROTOCOL GOVERNANCE",activation:"No global token ballot",shared:"Client / validator adoption",surfaces:["Protocol-development process","Client-adoption process"],watch:["ACPs","Client releases","Validator / network adoption","Major upgrades"]}
};
